//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiTableTopGameMaster.ConsoleApp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AiTableTopGameMaster.Adventures.IslandAdventureDemo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Backstory {
            get {
                return ResourceManager.GetString("Backstory", resourceCulture);
            }
        }
        
        internal static string IslandDescription {
            get {
                return ResourceManager.GetString("IslandDescription", resourceCulture);
            }
        }
        
        internal static string NarrativeStructure {
            get {
                return ResourceManager.GetString("NarrativeStructure", resourceCulture);
            }
        }
        
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        internal static string Encounters {
            get {
                return ResourceManager.GetString("Encounters", resourceCulture);
            }
        }
        
        internal static string LocationWreckSite {
            get {
                return ResourceManager.GetString("LocationWreckSite", resourceCulture);
            }
        }
        
        internal static string LocationJungleShack {
            get {
                return ResourceManager.GetString("LocationJungleShack", resourceCulture);
            }
        }
        
        internal static string LocationRitualCave {
            get {
                return ResourceManager.GetString("LocationRitualCave", resourceCulture);
            }
        }
        
        internal static string LocationCollapsedWatchtower {
            get {
                return ResourceManager.GetString("LocationCollapsedWatchtower", resourceCulture);
            }
        }
        
        internal static string LocationReefCircle {
            get {
                return ResourceManager.GetString("LocationReefCircle", resourceCulture);
            }
        }
        
        internal static string EncounterCrabSwarm {
            get {
                return ResourceManager.GetString("EncounterCrabSwarm", resourceCulture);
            }
        }
        
        internal static string EncounterKoboldPatrol {
            get {
                return ResourceManager.GetString("EncounterKoboldPatrol", resourceCulture);
            }
        }
        
        internal static string EncounterTrappedDrawer {
            get {
                return ResourceManager.GetString("EncounterTrappedDrawer", resourceCulture);
            }
        }
        
        internal static string EncounterTheRitual {
            get {
                return ResourceManager.GetString("EncounterTheRitual", resourceCulture);
            }
        }
        
        internal static string EncounterVisionsOfTheDeep {
            get {
                return ResourceManager.GetString("EncounterVisionsOfTheDeep", resourceCulture);
            }
        }
        
        internal static string GameMasterGuidance {
            get {
                return ResourceManager.GetString("GameMasterGuidance", resourceCulture);
            }
        }
    }
}
